api_get_ad:
  path: /api/ad/{id}
  controller: App\Controller\AdController::getAd
  methods: GET

api_post_ad:
  path: /api/ad
  controller: App\Controller\AdController::postAd
  methods: POST
api_put_ad:
  path: /api/ad/{id}
  controller: App\Controller\AdController::putAd
  methods: PUT
api_delete_ad:
  path: /api/ad/{id}
  controller: App\Controller\AdController::deleteAd
  methods: DELETE